version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing app dependencies...
      - yarn install
  build:
    commands:
      - echo Building application...
      - yarn build
  post_build:
    commands:
      - aws s3 sync build/ s3://staging.wocrip.org --delete
